# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    ubuntu-16.04:
      imageName: 'ubuntu-16.04'
    mac-high-sierra-10.13:
      imageName: 'macOS-10.13'
    mac-mojave-10.14:
      imageName: 'macOS-10.14'
    windows-vs2017:
      imageName: 'vs2017-win2016'
    windows-vs2019:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

variables:
  build_dir: $(Agent.BuildDirectory)/build

steps:
  - script: pwd
  - script: mkdir $(build_dir)
  - script: cmake ..
    workingDirectory: $(build_dir)
  - script: cmake --build . -- -j2
    workingDirectory: $(build_dir)
  - script: ctest -j2 --output-on-failure
    workingDirectory: $(build_dir)
  - script: echo $(Agent.BuildDirectory)
  - script: echo $(Agent.OS)

