# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    ubuntu-18.04:
      imageName: 'ubuntu-18.04'
    ubuntu-16.04:
      imageName: 'ubuntu-16.04'
    macOS-mojave-10.14:
      imageName: 'macOS-10.14'
    macOS-high-sierra-10.13:
      imageName: 'macOS-10.13'
    windows-vs2019:
      imageName: 'windows-2019'
    windows-vs2017:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
  - script: echo $(Agent.OS)
    displayName: print os

  - script: cmake .
    displayName: cmake

  - script: cmake --build .
    displayName: build

  - script: ctest --output-on-failure
    displayName: ctest
